# Generated by Django 3.2.20 on 2023-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texttospeech',
            old_name='first_name',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='texttospeech',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
